export const CREATE_ADVERT = 'CREATE_ADVERT';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const CREATE_ADVERT_ERROR = 'CREATE_ADVERT_ERROR';

export const DELETE_ADVERT = 'DELETE_ADVERT';
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS';
export const DELETE_ADVERT_ERROR = 'DELETE_ADVERT_ERROR';

export const INIT_ADVERT = 'INIT_ADVERT';
export const INIT_ADVERT_SUCCESS = 'INIT_ADVERT_SUCCESS';
export const INIT_ADVERT_ERROR = 'INIT_ADVERT_ERROR';

export const SEARCH_ADVERTS = 'SEARCH_ADVERTS';
export const SEARCH_ADVERTS_SUCCESS = 'SEARCH_ADVERTS_SUCCESS';
export const SEARCH_ADVERTS_ERROR = 'SEARCH_ADVERTS_ERROR';

export const SEARCH_MORE_ADVERTS = 'SEARCH_MORE_ADVERTS';
export const SEARCH_MORE_ADVERTS_SUCCESS = 'SEARCH_MORE_ADVERTS_SUCCESS';
export const SEARCH_MORE_ADVERTS_ERROR = 'SEARCH_MORE_ADVERTS_ERROR';
