export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR';

export const INIT_BOOKINGS = 'INIT_BOOKINGS';
export const INIT_BOOKINGS_SUCCESS = 'INIT_BOOKINGS_SUCCESS';
export const INIT_BOOKINGS_ERROR = 'INIT_BOOKINGS_ERROR';
