export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const INIT_COMMENT = 'INIT_COMMENT';
export const INIT_COMMENT_SUCCESS = 'INIT_COMMENT_SUCCESS';
export const INIT_COMMENT_ERROR = 'INIT_COMMENT_ERROR';
