export const INIT_CHAT_TOKEN = 'INIT_CHAT_TOKEN';
export const INIT_CHAT_TOKEN_SUCCESS = 'INIT_CHAT_TOKEN_SUCCESS';
export const INIT_CHAT_TOKEN_ERROR = 'INIT_CHAT_TOKEN_ERROR';
export const CHAT_TOKEN_DELETE = 'INIT_CHAT_TOKEN_DELETE';

export const INIT_CHAT_CLIENT = 'INIT_CHAT_CLIENT';
export const INIT_CHAT_CLIENT_SUCCESS = 'INIT_CHAT_CLIENT_SUCCESS';
export const INIT_CHAT_CLIENT_ERROR = 'INIT_CHAT_CLIENT_ERROR';
export const CHAT_CLIENT_DELETE = 'INIT_CHAT_CLIENT_DELETE';
