export const INIT_MAP_LOADING = "INIT_MAP_LOADING";
export const INIT_MAP_SUCCESS = "INIT_MAP_SUCCESS";
export const INIT_MAP_ERROR = "INIT_MAP_ERROR";

export const DELETE_MAP_LOADING = "DELETE_MAP_LOADING";
export const DELETE_MAP_SUCCESS = "DELETE_MAP_SUCCESS";
export const DELETE_MAP_ERROR = "DELETE_MAP_ERROR";
