export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const INIT_INFO = 'INIT_INFO';
export const INIT_INFO_SUCCESS = 'INIT_INFO_SUCCESS';
export const INIT_INFO_ERROR = 'INIT_INFO_ERROR';
